name: PR Update
"on":
  pull_request:
    branches:
      - main
concurrency: production
jobs:
  changelog:
    name: PR Update
    runs-on: ubuntu-latest
    steps:

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Use Next Version
        if: ${{ steps.semver.outputs.next != '' }}
        run: |
          echo ${{ steps.semver.outputs.next }}
        env:
          TZ: UTC
