name: PR Merge
"on":
  pull_request:
    branches:
      - main
    types:
      - closed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  merge:
    name: PR Merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent

      - name: "Create New Tag"
        if: ${{ steps.semver.outputs.next != '' }}
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PAT }}
          custom_tag: ${{ steps.semver.outputs.next }}
          tag_prefix: ""
