name: PR Merge
"on":
  pull_request:
    branches:
      - main
    types:
      - closed
concurrency: production
jobs:
  release:
    name: PR Merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent

      - name: "Use Next Version: Create New Tag"
        if: ${{ steps.semver.outputs.next != '' }}
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          github_token: ${{ secrets.PAT }}
          tag: "${{ steps.semver.outputs.next != '' }}"
          tag_exists_error: true
          message: ""
