name: Push
"on":
  push:
    branches:
      - main
concurrency: production
jobs:

  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent

      - name: "Use Next Version: Create New Tag"
        if: ${{ steps.semver.outputs.next != '' }}
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.PAT  }}
          tag: ${{ steps.semver.outputs.next }}

  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Rebase all pull requests on push to the main branch
        uses: peter-evans/rebase@v3
        with:
          base: main
          exclude-drafts: true
          exclude-labels: |
            no-rebase
