name: Push Create Tag
"on":
  push:
    branches:
      - main
concurrency: production
jobs:
  create:
    name: Push  Create Tag
    runs-on: ubuntu-latest
    steps:

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent

      - name: "Use Next Version: Create New Tag"
        if: ${{ steps.semver.outputs.next != '' }}
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          CUSTOM_TAG: ${{ steps.semver.outputs.next }}
