name: Push Rebase
"on":
  push:
    branches:
      - main
concurrency:
  group: push-rebase
  cancel-in-progress: true
jobs:
  rebase:
    name: Push Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Rebase all pull requests on push to the main branch
        uses: peter-evans/rebase@v3.0.0
        with:
          base: main
          exclude-drafts: true
          exclude-labels: |
            no-rebase
            dependencies
