name: Release
"on":
  pull_request:
    branches:
      - main
    types:
      - closed
concurrency: production
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -y install --no-install-recommends git-buildpackage
      # - uses: actions/checkout@v3

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Update debian/changelog
        if: ${{ steps.semver.outputs.nextStrict != '' }}
        run: |
          # export DEBFULLNAME=$(grep '^Maintainer:' debian/control | cut -d : -f 2 | cut -d '<' -f 1 | xargs echo)
          # export DEBEMAIL=$(grep '^Maintainer:' debian/control | cut -d '<' -f 2 | tr -d '>')
          # git config --local user.name "$DEBFULLNAME"
          # git config --local user.email "$DEBEMAIL"
          #
          echo ${{ steps.semver.outputs.nextStrict }}
        env:
          TZ: UTC0

      # - name: "Commit all changed changelogs back to the repository"
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_options: '--signoff'
      #     push_options: '--force'
      #     branch: "main"
      #     file_pattern: 'debian/changelog CHANGELOG.md'
      #     commit_message: "docs: Saving generated changelogs"
